version: '3.9'

services:
  web:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"
    restart: always
    depends_on:
      - php
      - db

  php:
    build:
      context: ./docker
    restart: always
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/var/www/html/
    environment:
      - DSN=${DSN}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db

  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5431:5432"
    volumes:
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data: